---
- name: Play for downloading from a private github repo
  hosts: localhost
  vars:
    download_dir: "{{ playbook_dir }}/tmp_download/"
    package_dir: "{{ playbook_dir }}/tmp_install/"
  
  tasks:
    # - name: Install required packages
    #   ansible.builtin.apt:
    #     name: [unzip]
    #     state: present

    - name: Create download directory
      ansible.builtin.file:
        path: "{{ download_dir }}"
        state: directory
        mode: "0755"
    
    - name: Create package directory
      ansible.builtin.file:
        path: "{{ package_dir }}"
        state: directory
        mode: "0755"

    - name: Load Variables from json file
      ansible.builtin.include_vars:
        file: "{{ json_file }}"
        name: package_config

#######################
# Start Download 
#######################

    - name: Get details of the latest release
      ansible.builtin.uri:
        url: "https://api.github.com/repos/{{package_config.organization}}/{{package_config.repository}}/releases"
        headers:
          Accept: "application/vnd.github.v3+json"
          Authorization: token {{ lookup('ansible.builtin.env', package_config.token_name) }}
          X-GitHub-Api-Version: 2022-11-28
        return_content: true
      register: latest_release_info

    - name: Extract download_link
      ansible.builtin.set_fact:
        download_link: "{{ latest_release_info | community.general.json_query('json[0].assets[0].id') }}"

    - name: Download archive
      ansible.builtin.get_url:
        url: "https://api.github.com/repos/{{package_config.organization}}/{{package_config.repository}}/releases/assets/{{ download_link }}"
        headers:
          Accept: "application/octet-stream"
          Authorization: Bearer {{ lookup('ansible.builtin.env', package_config.token_name) }}
          X-GitHub-Api-Version: 2022-11-28
        dest: "{{ download_dir }}"
        mode: "0644"
      register: dowloaded_file

    - name: Print filename 1 
      ansible.builtin.debug:
        msg: "Downloaded file: {{ dowloaded_file.dest }}"

    - name: Extract tar.gz file
      ansible.builtin.unarchive:
        src: "{{ dowloaded_file.dest }}"
        dest: "{{ package_dir }}"
      register: file_to_copy
      when: dowloaded_file.dest.endswith('.tar.gz')
    
    - name: Set file_to_copy if whl package
      ansible.builtin.set_fact:
        file_to_copy: "{{ dowloaded_file.dest }}"
      when: dowloaded_file.dest.endswith('.whl')

    - name: Print filename 2
      ansible.builtin.debug:
        msg: "After unpacking: {{ file_to_copy }}"

    - name: Copy whl file
      ansible.builtin.copy:
        src: "{{ file_to_copy }}"
        dest: "{{ package_dir }}"
        mode: "0755"

    # there are multiple branches needed, depending on the file type
    - name: Print filename
      ansible.builtin.debug:
        msg: "Finished: {{ file_to_copy }}"
