---
- name: Start container and install dependecies within it
  hosts: localhost
  gather_facts: false
  vars:
    container_name: stm32hal
    workspace_dir: /home/developer/workspace
    packages_dir: "{{ workspace_dir }}/repo_config/ansible/tmp_install"
    virtualenv: "{{ workspace_dir }}/.venv_container"
  tasks:

    - name: Set Repo_root for Mount
      ansible.builtin.shell: git rev-parse --show-toplevel
      register: repo_root 

    - name: Start container
      community.docker.docker_container:
        cleanup: true
        command: bash
        detach: true
        interactive: true
        image: stm32
        name: "{{ container_name }}"
        output_logs: true
        state: started
        mounts:
          - type: bind
            source: "{{ repo_root.stdout }}"
            target: "{{ workspace_dir }}"

    - name: Create Container Virtual Environment
      community.docker.docker_container_exec:
        container: "{{ container_name }}"
        command: "python3 -m venv {{ virtualenv }}"

    - name: Install Requirements
      community.docker.docker_container_exec:
        container: "{{ container_name }}"
        command: bash -c "source {{ virtualenv }}/bin/activate && pip install -r {{ workspace_dir }}/requirements.txt"
    
    - name: Install Downloaded Packages
      community.docker.docker_container_exec:
        container: "{{ container_name }}"
        command: bash -c "source {{ virtualenv }}/bin/activate && pip install {{ packages_dir }}/*"
  #######
  # Container is running: Test, Compile
  #######
    - name: Run Tests
      community.docker.docker_container_exec:
        container: "{{ container_name }}"
        command: bash -c "source {{ virtualenv }}/bin/activate && pytest -s -v {{ workspace_dir }}/tests/"
        chdir: "{{ workspace_dir }}"
        

    - name: Stop & Remove Container
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent