name: C/C++ CI

on:
  push:
    branches: [ "feature/pipeline" ]
  pull_request:
    branches: [ "feature/pipeline" ]

jobs:
  build:

    runs-on: self-hosted
    container:
        image: stm32

    steps:
    - uses: actions/checkout@v4
    
    - name: run_tests
      run: echo "hello world!"
