name: Compile Tests

on:
  push:
  pull_request:
    branches: [ "master" ]
  workflow_call:

jobs:
  get_dependencies:

    runs-on: self-hosted
    permissions: 
      packages: read
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    
    - name: Pull Image
      run: docker pull ghcr.io/dietwall/arm_gcc_image:latest

    - name: setup ansible environment
      run: ./repo_config/setup_env.sh

    - name: Download dependencies
      run: ./repo_config/download.sh
    
  