name: Workspace init

on:
  push:
    branches: [ "feature/ci" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    permissions: write-all
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: 'recursive'
    
    - name: setup ansible environment
      run: ./repo_config/setup_env.sh
      env:
        TCL_UTILS_TOKEN: ${{ secrets.TCL_UTILS_TOKEN }}
        REPO_HELPER_TOKEN: ${{ secrets.REPO_HELPER_TOKEN }}
    
    - name: Start Container
      run: source repo_config/.venv_installation/bin/activate && ansible-playbook -c local repo_config/ansible/setup_container.yml

    - name: Archive Test Results
      run: tar -czvf test_results.tar.gz test_build/

    - name: Print Directory
      run: ls -la
    
    - name: Upload Test Results  
      uses: actions/upload-artifact@v4
      with:
          name: test-results
          path: test_results.tar.gz
    
    - name: publish test_results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: (!cancelled())
      with:
        files: |
          test_results.xml
            