name: Compile Tests

on:
  push:
  pull_request:
    branches: [ "master" ]
  workflow_call:

jobs:
  login:
    runs-on: self-hosted
    permissions: 
      packages: read
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    # - name: Login to GitHub Container Registry
    #   run: echo "${{ secrets.GHCR_LOGIN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    
    - name: Pull Image
      run: docker pull ghcr.io/dietwall/arm_gcc_image:latest
