name: Compile Tests

on:
  workflow_call:

jobs:
  get_dependencies:
    runs-on: self-hosted
    permissions: 
      packages: read
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    
    # this does not require an explicit login, if host is already logged in
    - name: Pull Image 
      run: docker pull ghcr.io/dietwall/arm_gcc_image:latest

    - name: setup ansible environment
      run: ./repo_config/setup_env.sh

    - name: Download dependencies
      run: ./repo_config/download.sh
      env:
        TCL_UTILS_TOKEN: ${{ secrets.TCL_UTILS_TOKEN }}
        REPO_HELPER_TOKEN: ${{ secrets.REPO_HELPER_TOKEN }}
    
    # we might do this with a standard dockerfile, or with repo_ops.py
    - name: Setup Container 
      run: source repo_config/.venv_installation/bin/activate && ansible-playbook -c local repo_config/ansible/setup_container.yml

  