name: Release Package

on:
    workflow_dispatch:
      inputs:
        version:
          description: 'Version to release'
          required: true
          default: '0.2.0'

jobs:
    test:
        permissions: write-all
        uses: ./.github/workflows/test.yml
        secrets: inherit
    
    build:
        permissions: write-all
        runs-on: self-hosted
        needs: test
        steps:
        - name: Checkout code
          uses: actions/checkout@v5

        - name: setup host environment
          run: ./repo_config/setup_env.sh
          env: 
            TOKEN: ${{ secrets.REPO_HELPER_TOKEN }}
        
        - name: create container
          run: source repo_config/.venv_host/bin/activate && ./repo_ops.py --operation start_container

        - name: configure hal package
          run: source repo_config/.venv_host/bin/activate && ./repo_ops.py --operation configure
        
        - name: build hal package
          run: source repo_config/.venv_host/bin/activate && ./repo_ops.py --operation build
        
        - name: package hal
          run: source repo_config/.venv_host/bin/activate && ./repo_ops.py --operation package

        - name: Upload package as artifact
          uses: actions/upload-artifact@v7
          with:
            name: TAR
            path: STM32F7_HAL*.tar.gz

