name: Test Compilation

on:
  push:
  workflow_call:

jobs:  
    test:
        runs-on: self-hosted
        steps:
        - name: Checkout code
          uses: actions/checkout@v5
        
        - name: setup host environment
          run: ./repo_config/setup_env.sh
          env: 
            TOKEN: ${{ secrets.REPO_HELPER_TOKEN }}
        
        - name: Pull Image
          run: docker pull ghcr.io/dietwall/arm_gcc_image:latest

        - name: create container
          run: ./repo_ops.py --operation start_container


        #- name: Publish Test Results
          # uses: EnricoMi/publish-unit-test-result-action/linux@v2
          # if: (!cancelled())
          # with:
          #   files:  |
          #       test_results*.xml
        
    build:
        runs-on: self-hosted
        needs: test
        steps:
        - name: Checkout code
          uses: actions/checkout@v5
        
        - name: setup ansible environment
          run: ./repo_config/setup_env.sh

        - name: Download dependencies
          run: ./repo_config/download.sh
          env:
            TCL_UTILS_TOKEN: ${{ secrets.TCL_UTILS_TOKEN }}
            REPO_HELPER_TOKEN: ${{ secrets.REPO_HELPER_TOKEN }}
        
        # we might do this with a standard dockerfile, or with repo_ops.py
        #- name: Setup Container 
        #  run: source repo_config/.venv_installation/bin/activate && ansible-playbook -c local repo_config/ansible/setup_container.yml

        - name: check container 
          run: docker container ls -a

        - name: check venv
          run: ls -la
  